environment:
  ProductVersion: 0.9


init:
  - ps: >-
      if ($env:APPVEYOR_REPO_BRANCH -eq "master")
      {
          Update-AppveyorBuild -Version "$env:ProductVersion.$env:APPVEYOR_BUILD_NUMBER"         
      }
      else
      {
          Update-AppveyorBuild -Version "$env:ProductVersion.$env:APPVEYOR_BUILD_NUMBER-$env:APPVEYOR_REPO_BRANCH"
      }
      Set-AppveyorBuildVariable "FileVersion" "$env:ProductVersion.0.$env:APPVEYOR_BUILD_NUMBER"

image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '$(FileVersion)'
  file_version: '$(FileVersion)'
  informational_version: '$(FileVersion)'
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  server: https://www.myget.org/F/artice/api/v2/package
  api_key:
    secure: 16bnEoTAw97sQU9DAAzFuO5yWGGCQaKRo5HSRKaP3IuqWVDcPWzDKgRrQhtpEaq2
  skip_symbols: true
  artifact: /.*\.nupkg/
  