version: 0.9.{build}-{branch}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}$(package_suffix)'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  server: https://www.myget.org/F/artice-test/api/v2/package
  api_key:
    secure: 16bnEoTAw97sQU9DAAzFuO5yWGGCQaKRo5HSRKaP3IuqWVDcPWzDKgRrQhtpEaq2
  skip_symbols: true
  artifact: /.*\.nupkg/
  