version: 0.9.0
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  server: https://www.myget.org/F/artice-test/api/v2/package
  api_key:
    secure: 16bnEoTAw97sQU9DAAzFuO5yWGGCQaKRo5HSRKaP3IuqWVDcPWzDKgRrQhtpEaq2
  skip_symbols: true
  artifact: /.*\.nupkg/