environment:
  ProductVersion: 0.10

  CODECOV_TOKEN:
    secure: tfuWf0tytpb8+HItUm0jhB/sXOx0K3GJMHLbn3+FKV1EfnCncRE6iAHz0Ytlt9nC


branches:
  only:
  - master
  - dev

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_BRANCH -eq "master")
      {
          Update-AppveyorBuild -Version "$env:ProductVersion.$env:APPVEYOR_BUILD_NUMBER"         
      }
      else
      {
          Update-AppveyorBuild -Version "$env:ProductVersion.$env:APPVEYOR_BUILD_NUMBER-$env:APPVEYOR_REPO_BRANCH"
      }
      Set-AppveyorBuildVariable "FileVersion" "$env:ProductVersion.0.$env:APPVEYOR_BUILD_NUMBER"

image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '$(FileVersion)'
  file_version: '$(FileVersion)'
  informational_version: '$(FileVersion)'

before_build:
- dotnet restore
- choco install opencover.portable
- choco install codecov

build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  server: https://www.myget.org/F/artice/api/v2/package
  api_key:
    secure: 16bnEoTAw97sQU9DAAzFuO5yWGGCQaKRo5HSRKaP3IuqWVDcPWzDKgRrQhtpEaq2
  skip_symbols: true
  artifact: /.*\.nupkg/

test_script:
- OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:test -filter:"+[Artice*]* -[*.Tests]* -[*.Testing*]*" -output:".\Artice_coverage.xml" -oldstyle
- codecov -f "Artice_coverage.xml"
  